### ISSUE TITLE
authorizationCode grant type doesn't work from swagger UI

### ISSUE THREAD

**Issue by KorvinSzanto** [concretecms/concrete_api_proposal_2022#1]
I get a 404 when I try to authenticate using the swagger UI

**Comment by aembler** [comment]
Can you post a video or something? Not seeing this.

![ScreenFlow](https://user-images.githubusercontent.com/527809/183718455-767fcc1b-544e-4ed8-bbbd-eff77331ec38.gif)

Note: if you're having trouble with this it's possible you didn't let the API proposal package create the API integration on installation. You'll want it to create the API integration so it can do so in a way where it can reuse the client id/secret
