### ISSUE TITLE
Available to guess file id from uuid?

### ISSUE THREAD

**Issue by hissy** [concretecms/concrete_api_proposal_2022#4]
How about using uuid only?

**Comment by aembler** [comment]
Yeah, that's an important point and a really good suggestion. I think we ought to do the following:

1. Everywhere the file transformer is used, for the ID return value return either a UUID if it exists, or fall back to the numerical ID if it doesn't (just like we do elsewhere in the core.) This means for most modern sites file IDs will appear as UUIDs everywhere.
2. Modify the $fileID parameters in all file processing API calls to take either a UUID or fall back to a file ID as we do elsewhere in the core. So file IDs can still work if your system hasn't been updated to use UUIDs but in most cases you'll be using UUIDs.

What I don't want is to have numerical file IDs live alongside UUIDs, and devs having to guess which one to use.
